### ISSUE TITLE
risk score comparisons between pkg versions

### ISSUE THREAD

**Issue by Xyarz** [pharmaR/riskassessment#602] opened 2023-08-01 12:52 UTC
Per feedback from useR@ 2023 conf in Basel, the ask was whether it would be possible to also include/assess the risks for R-packages in its different versions and show trends, changes and comparisons of different versions of such.

Here I could see the [riskscore](https://github.com/pharmaR/riskscore) pkg providing lots of help as it assesses whole of CRAN.

**Comment by aclark02-arcus** [comment] 2024-07-03 16:15
duplicate of related #253, #254, and #255

**Closed by aclark02-arcus** 2024-07-03 16:15 UTC
Labels: enhancement
