### ISSUE TITLE
Ability to type in package names

### ISSUE THREAD

**Issue by thebioengineer** [pharmaR/riskassessment#248] opened 2022-06-14 15:51 UTC
Currently the app expects users to upload a csv with package and version. This takes users outside the app and adds friction. It would be nice to have the ability to write a package name and version directly in the UI of the app.

**Comment by AARON-CLARK** [comment] 2022-06-14 15:59
Duplicate of #247, but we'll keep open since #247 contains multiple issues.

Thanks for the feedback @thebioengineer! We were already starting to make mental preparations for this upgrade (at least for CRAN packages). What do you think of the UI experience on [diffify](https://diffify.com/R/shiny/1.7.0/1.7.1)? Does it fulfill your needs from an ease-of-use perspective?

**Comment by AARON-CLARK** [comment] 2023-01-31 15:45
closed with #327 and #329

**Closed by AARON-CLARK** 2023-01-31 15:45 UTC
