### ISSUE TITLE
PDF Report Download Not Working

### ISSUE THREAD

**Issue by Jeff-Thompson12** [pharmaR/riskassessment#489] opened 2023-04-12 14:26 UTC
The PDF downloads are no longer working. It gets hung indefinitely.

**Comment by AARON-CLARK** [comment] 2023-04-12 18:57
perhaps a duplicate of #458, but last time this happened to me and @Robert-Krajcik locally, we just had to updated our tiny_tex installation via [these debugging tips](https://yihui.org/tinytex/r/#debugging), right Robert?

**Comment by AARON-CLARK** [comment] 2023-04-13 18:49
Seems to be working with me on branch proposed in #490. Could you please re-test and close issue as needed?

**Comment by AARON-CLARK** [comment] 2023-04-13 19:45
@Jeff-Thompson12, just kidding. The PDF download worked because I was on a different version of `Chromote`:

![image](https://user-images.githubusercontent.com/17878953/231865231-cedaf1e4-1990-4706-9766-fb508d12895b.png)

When I restored to v0.1.1 per the `renv` lock file, the PDF download failed. @Jeff-Thompson12, I did bump `chromote` to `main` (v0.1.1.9001) due to your comment on #447 and the PDFs downloads are still failing. So the question becomes, why did we bump up to v0.1.1 in the first place (was it for `shinytest2` tests?) and should we revert back to v0.1.0 to keep our PDF reports working?

**Comment by Jeff-Thompson12** [comment] 2023-04-13 19:51
We can certainly explore that option. I don't understand how these two things are related though. And that troubles me.

**Comment by AARON-CLARK** [comment] 2023-04-18 19:01
@Jeff-Thompson12, I just tried to revert back to `chromote v0.1.0` to test (again), and the PDF download hung indefinitely. So I guess we can abandon that theory... which was working last week. So strange.
```r
remotes::install_version("chromote", version = "0.1.0", repos = "http://cran.us.r-project.org")
packageVersion("chromote")
>  ‘0.1.0’
```

**Comment by Jeff-Thompson12** [comment] 2023-04-18 19:24
@AARON-CLARK  what else changed from 5 days ago?

**Comment by AARON-CLARK** [comment] 2023-04-19 16:15
🤷🏼‍♂️

**Comment by ScottSchumacker** [comment] 2023-04-25 00:56
I just checked this locally and it appears to be working on my end. Is this still an issue?

**Comment by AARON-CLARK** [comment] 2023-05-09 13:15
Randomly started working for me today! Per slack, seems to be working for @Jeff-Thompson12 & @ScottSchumacker, so I will gleefully close.

**Closed by AARON-CLARK** 2023-05-09 13:15 UTC
Labels: bug
